Traceback (most recent call last):
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/tokenization_utils_base.py", line 2315, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/models/wav2vec2_phoneme/tokenization_wav2vec2_phoneme.py", line 136, in __init__
    self.init_backend(self.phonemizer_lang)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/models/wav2vec2_phoneme/tokenization_wav2vec2_phoneme.py", line 182, in init_backend
    requires_backends(self, "phonemizer")
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/utils/import_utils.py", line 2118, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
Wav2Vec2PhonemeCTCTokenizer requires the phonemizer library but it was not found in your environment. You can install it with pip:
`pip install phonemizer`. Please note that you may need to restart your runtime after installation.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/tts2/home/joregan/ls_phone.py", line 10, in <module>
    pipe = pipeline(model=MODEL)
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/pipelines/__init__.py", line 1059, in pipeline
    raise e
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/pipelines/__init__.py", line 1054, in pipeline
    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_identifier, use_fast=use_fast, _from_pipeline=task, **hub_kwargs, **tokenizer_kwargs
    )
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/models/auto/tokenization_auto.py", line 1116, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/tokenization_utils_base.py", line 2069, in from_pretrained
    return cls._from_pretrained(
           ~~~~~~~~~~~~~~~~~~~~^
        resolved_vocab_files,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/tokenization_utils_base.py", line 2316, in _from_pretrained
    except import_protobuf_decode_error():
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/joregan/miniconda3/lib/python3.13/site-packages/transformers/tokenization_utils_base.py", line 87, in import_protobuf_decode_error
    raise ImportError(PROTOBUF_IMPORT_ERROR.format(error_message))
ImportError: 
 requires the protobuf library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

